#!/usr/bin/env python3
"""
Regenerate all recipe scripts from recipes.csv
Ensures all recipes have correct parts from the source data
"""

import csv
import os
from pathlib import Path

# Paths
CSV_PATH = "/Users/danielreis/Documents/3D_PRINTING/MODELS/154. Stackables/000.STACKABLES-STARTER-SET/Recipes/recipes.csv"
STL_BASE = "/Users/danielreis/Documents/3D_PRINTING/MODELS/154. Stackables/ETSY_EXPORTS-AND-PACKAGING/02-ALIGNED-STLS"
RECIPES_BASE = "/Users/danielreis/Documents/3D_PRINTING/MODELS/154. Stackables/000.STACKABLES-STARTER-SET/PRINT FILES/11 Recipes"

# CSV column to folder name mapping
COLUMN_TO_RECIPE = {
    "3 Even": "3-Even",
    "2+1 Tall": "2-plus-1-Tall",
    "1 Tall 1 secret": "1-Tall-1-Secret",
    "3 steps": "3-Steps",
    "Mega 2x secret": "Mega-2x-Secret",
    "3 steps w/ Mini": "3-Steps-with-Mini",
    "2 w/ secret": "2-with-Secret",
    "2 w/ Top Bowl": "2-with-Top-Bowl",
    "Capped 1 super": "Capped-1-Super",
    "2 w/ Top 2": "2-with-Top-2",
    "2+1 Mini": "2-plus-1-Mini",
}

def find_stl(filename):
    """Find full path for an STL file in the aligned-stls directory"""
    if not filename or filename.strip() == "":
        return None
    
    # Handle typo in CSV: top--tlat should be top--flat
    filename = filename.replace("top--tlat", "top--flat")
    
    # Handle CSV variants (_1, _2, etc.) - these map to same base file
    # e.g., "middle--flat--01--xs-18.0mm--ribbed_1.stl" → "middle--flat--01--xs-18.0mm--ribbed.stl"
    if "_1.stl" in filename or "_2.stl" in filename:
        # Remove the _N suffix before .stl
        base = filename.rsplit("_", 1)[0] + ".stl"
        filename = base
    
    for root, dirs, files in os.walk(STL_BASE):
        for file in files:
            if file == filename:
                return os.path.join(root, file)
    
    return None

def extract_parts(csv_data, recipe_col):
    """Extract parts for all stacks from CSV data"""
    stacks = {"A": [], "B": [], "C": []}
    
    for row in csv_data:
        position = row.get("Position", "").strip()
        part_name = row.get(recipe_col, "").strip()
        
        if not part_name or part_name == "":
            continue
        
        # Parse position like "Stack A Part 1"
        if position.startswith("Stack"):
            parts = position.split()
            stack_letter = parts[1]  # "A", "B", or "C"
            
            if stack_letter in stacks:
                full_path = find_stl(part_name)
                if full_path:
                    stacks[stack_letter].append(full_path)
                else:
                    print(f"  ⚠️  Missing: {part_name}")
    
    return stacks

def generate_recipe_script(recipe_name, stack_letter, parts):
    """Generate a recipe script"""
    
    export_dir = f"/Users/danielreis/Documents/3D_PRINTING/MODELS/154. Stackables/000.STACKABLES-STARTER-SET/PRINT FILES/11 Recipes/{recipe_name}/Stack-{stack_letter}"
    
    parts_str = ""
    for part in parts:
        parts_str += f'    r"{part}",\n'
    
    script = f'''import os

# Generated by Recipe Regenerator - 2026-07-11
# Recipe: {recipe_name} - Stack {stack_letter}

# ==============================================================================
# 1. RECIPE CONFIGURATION
# ==============================================================================
# Recipe name
RECIPE_NAME = "{recipe_name}--Stack-{stack_letter}"

# Stack direction: "TOP_TO_BOTTOM" or "BOTTOM_TO_TOP"
STACK_DIRECTION = "TOP_TO_BOTTOM"

# Parts in order (full paths)
ASSEMBLY_PARTS = [
{parts_str}]

# ==============================================================================
# 2. AUTOMATED RUNNER (DO NOT EDIT)
# ==============================================================================
BASE_ROOT = "/Users/danielreis/Documents/3D_PRINTING/MODELS/154. Stackables"
ENGINE_PATH = os.path.join(BASE_ROOT, "BLENDER_RECIPE-BUILDER", "SCRIPTS", "ASSEMBLE_RECIPE.py")

# Export directory is this script's folder
EXPORT_DIR = r"{export_dir}"

def main():
    if not os.path.exists(ENGINE_PATH):
        print(f"Error: Engine not found at {{ENGINE_PATH}}")
        return
    
    with open(ENGINE_PATH, 'r') as f:
        exec(f.read(), {{
            'RECIPE_NAME': RECIPE_NAME,
            'ASSEMBLY_PARTS': ASSEMBLY_PARTS,
            'STACK_DIRECTION': STACK_DIRECTION,
            'EXPORT_DIR': EXPORT_DIR,
            '__name__': '__main__'
        }})

if __name__ == "__main__":
    main()
'''
    return script

def main():
    print("="*70)
    print("REGENERATING RECIPES FROM CSV")
    print("="*70)
    
    # Read CSV
    with open(CSV_PATH, 'r') as f:
        reader = csv.DictReader(f)
        csv_data = list(reader)
    
    print(f"\n✓ Read CSV with {len(csv_data)} rows\n")
    
    # Process each recipe
    for csv_col, recipe_name in COLUMN_TO_RECIPE.items():
        print(f"\n{recipe_name}:")
        
        # Extract parts for A, B, C
        stacks = extract_parts(csv_data, csv_col)
        
        # Generate scripts
        for stack_letter in ["A", "B", "C"]:
            parts = stacks[stack_letter]
            if not parts:
                print(f"  Stack-{stack_letter}: ⚠️  NO PARTS")
                continue
            
            stack_dir = os.path.join(RECIPES_BASE, recipe_name, f"Stack-{stack_letter}")
            script_path = os.path.join(stack_dir, f"Stack-{stack_letter}--STACKABLES-RECIPE.py")
            
            # Ensure directory exists
            os.makedirs(stack_dir, exist_ok=True)
            
            # Write script
            script_content = generate_recipe_script(recipe_name, stack_letter, parts)
            with open(script_path, 'w') as f:
                f.write(script_content)
            
            print(f"  Stack-{stack_letter}: ✓ {len(parts)} parts → {script_path}")
    
    print("\n" + "="*70)
    print("✅ REGENERATION COMPLETE")
    print("="*70)

if __name__ == "__main__":
    main()
